language:   scala
scala:      2.12.1
jdk:        oraclejdk8
sudo:       false

script:
    -   sbt coverage test coverageReport
    -   sbt clean jancyCommon/publish-m2 jancyTranspiler/publish-m2 examples/assembly

cache:
    directories:
        -   $HOME/.ivy2/cache
        -   $HOME/.sbt/boot/

before_cache:
    -   find $HOME/.ivy2 -name "ivydata-*.properties" -delete
    -   find $HOME/.sbt -name "*.lock" -delete
